export const businessName = "부산호빠";
export const venueName = "부산호빠";
export const area = "부산시 해운대구";
export const detailAddress = "마린시티2로 33";
export const phoneDisplay = "010-6773-6222";
export const phoneHref = "tel:01067736222";
export const managerName = "수빈실장";
export const kakaoOpenChatHref = "https://open.kakao.com/o/sPtygZQb";
export const siteUrl = "https://www.busanhopa.com";
export const fullAddress = `${area} ${detailAddress}`;
export const geocodingAddress = fullAddress;
const mapQuery = encodeURIComponent(fullAddress);
export const mapEmbedSrc = `https://www.google.com/maps?q=${mapQuery}&z=17&output=embed`;
export const mapDirectionsHref = `https://www.google.com/maps/dir/?api=1&destination=${mapQuery}`;
