export const businessName = "부산호빠";
export const venueName = "부산호빠";
export const area = "부산광역시 해운대구";
export const detailAddress = "해운대해변로298번길 25 영무파라드 호텔 지하 2층";
export const phoneDisplay = "010-6773-6222";
export const phoneHref = "tel:01067736222";
export const managerName = "부산호빠 매니저";
export const kakaoOpenChatHref = "https://open.kakao.com/o/busanhostbar";
export const siteUrl = "https://www.busanhostbar.kr";
export const fullAddress = `${area} ${detailAddress}`;
export const geocodingAddress = "부산광역시 해운대구 해운대해변로298번길 25";
export const latitude = 35.160941;
export const longitude = 129.1665417;
const mapQuery = encodeURIComponent(fullAddress);
export const mapEmbedSrc = `https://www.google.com/maps?q=${latitude},${longitude}&z=17&output=embed`;
export const mapDirectionsHref = `https://www.google.com/maps/dir/?api=1&destination=${mapQuery}`;
